name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run update script
        run: ./update.sh

      - name: Build and push
        run: |
          for d in $(find . -maxdepth 3 -type f -name "Dockerfile" | xargs -n1 dirname); do
            IMAGE_NAME="ghcr.io/${{ github.repository_owner }}/$(basename $(dirname $d))-$(basename $d):${GITHUB_REF_NAME}"
            docker buildx build --push -t "${IMAGE_NAME}" "$d"
          done
