name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run update script
        run: ./update.sh

      - name: Build and push
        run: |
          # The platforms we are building for
          PLATFORMS="linux/amd64,linux/arm/v5,linux/arm/v6,linux/arm/v7,linux/arm64,linux/386,linux/mips64le,linux/ppc64le,linux/riscv64,linux/s390x,windows/amd64-nanoserver-ltsc2022,windows/amd64-nanoserver-ltsc2025"

          # The name of the image
          IMAGE_NAME="ghcr.io/${{ github.repository_owner }}/hello-world"

          # The tags for the image
          TAGS="${IMAGE_NAME}:${GITHUB_REF_NAME}"

          # Build and push the image
          docker buildx build \
            --push \
            --tag "${TAGS}" \
            --platform "${PLATFORMS}" \
            .
